version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: uc-postgres
    environment:
      POSTGRES_USER: user_center
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_center
    ports:
      - "5543:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user_center"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: uc-redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
