spring:
  application:
    name: user-center
  profiles:
    default: local
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

auth:
  issuer-uri: ${AUTH_SERVER_ISSUER:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
